# Site
repository: its-dgreen/its-dgreen.github.io
favicon: images/favicon.ico

# Personal info
name: Dylan Green
title: Software Engineer and Problem Solver
email: dylan@ctrlaltdylan.com
website: ctrlaltdylan.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  its-dgreen
linkedin_username: ctrlaltdylan
twitter_username: its_dgreen

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | 
  Hey there, I'm Dylan, and I like to build software. I've worked on corporate software, government applications, brochureware, and even mobile apps. I have a passion for lifelong learning, and at any given time, I can be found learning some new technology or programming language 

  I am most skilled in: JavaScript, Data Analytics, and creating MVPs

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering,  some of my other interests and hobbies are:
   - Cooking
   - Playing D&D
   - Pokemon
   - Playing with my dogs   
   - Working out

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
